name: ethnomusicology_frontend
description: "Salamic Vibes - Music playlist app for Muslim family occasions"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.0
  dio: ^5.0.0
  flutter_riverpod: ^2.0.0
  go_router: ^14.0.0
  google_fonts: ^6.0.0
  flex_color_scheme: ^8.4.0
  flutter_animate: ^4.5.0
  responsive_framework: ^1.5.1
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.2.0

flutter:
  uses-material-design: true
